# this is a docker compose definition for creating the django application
# create the postgres service
version: '3'
services:
  db:
      image: postgres:latest
      volumes:
        - ~/postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=your_username
        - POSTGRES_PASSWORD=your_password
        - POSTGRES_DB=your_db_name
      networks:
        - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn whisper.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./whisper:/code
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network: